[project]
name = "package-segmenter"
version = "0.1.0"
description = "Segmenter Package for the Flow Project (flow-project.net)"
readme = "README.md"
authors = [
    { name = "Jonas Widmer", email = "jonas.widmer@students.ffhs.ch" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
package-segmenter = "package_segmenter:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
