[project]
name = "flow-segmenter"
version = "0.1.0"
description = "Segmenter Package for the Flow Project (flow-project.net)"
readme = "README.md"
authors = [
    { name = "Jonas Widmer", email = "jonas.widmer@unibe.ch" }
]
requires-python = ">=3.12"
dependencies = [
    "htrflow>=0.2.5",
    "kraken>=5.3.0",
    "lxml>=5.4.0",
    "numpy>=2.0.2",
    "pillow>=11.2.1",
    "shapely>=2.0.7",
]
