[build-system]
requires = [
    "setuptools",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "flow_segmenter"
version = "0.1.5"
description = "Segmenter Package for the Flow Project (flow-project.net)"
readme = { file = "README.md", content-type = "text/markdown" }
authors = [
    { name = "Jonas Widmer", email = "jonas.widmer@unibe.ch" },
    { name = "Dana Rebecca Meyer", email = "dameyer@techfak.uni-bielefeld.de" }
]
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
dependencies = [
    "htrflow>=0.2.6",
    "kraken>=6.0.2",
    "lxml>=6.0.2",
    "notebook>=7.4.7",
    "numpy>=1.26.4",
    "pillow>=11.3.0",
    "shapely>=2.0.6",
    "scipy>=1.13.0",
    "pydantic>=2.11.4",
    "scipy-stubs==1.16.0.2",
    "datasets>=4.0.0",
]
keywords = [
    "flow-project",
    "segmentation",
    "htrflow",
    "digital-humanities",
    "htr",
    "handwritten-text-recognition",
    "datasets",
    "huggingface",
    "nlp",
    "machine-learning",
]

[project.urls]
Homepage = "https://flow-project.net"
Repository = "https://github.com/The-Flow-Project/package-segmenter"
